apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "portafolio.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  DATABASE_URL: {{ include "portafolio.databaseUrl" . | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
